name: HeadUtility
version: '${project.version}'
main: me.geox25.headutility.HeadUtility
api-version: '1.20'

commands:
  headutility:
    description: "Main Plugin Command"
    usage: "/headutility <url | name> <value>"
    aliases:
      - hu
    permission: headutility.use